image: trion/ng-cli

stages:
  # - node_modules
  # - build
  - upload

# cache:
#   paths:
#     - node_modules/

# before_script:
#   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
#   - eval $(ssh-agent -s)
#   - echo "$SSH_PRIVATE_FILE" | tr -d '\r' | ssh-add - > /dev/null
#   - mkdir -p ~/.ssh
#   - chmod 700 ~/.ssh
#   - ssh-keyscan menkent.dev >> ~/.ssh/known_hosts
#   - chmod 644 ~/.ssh/known_hosts
#   # - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
#   # - chmod 644 ~/.ssh/known_hosts
#   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

# node_modules:
#   stage: node_modules
#   environment: Stage
#   script:
#     - rm ./package-lock.json
#     - npm i
#   only:
#     - master

# build_stage:
#   stage: build
#   environment: Stage
#   only:
#     - master
#   script:
#     - npm run toprod
#   artifacts:
#     expire_in: 1 day
#     paths:
#       - dist/SportPuzzle/

deploy:
  stage: upload
  environment: Stage
  only:
    - master
  script:
    # - apt-get update -qq && apt-get install -y -qq ssh rsync
    # - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    # - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # - mkdir -p ~/test && chmod 700 ~/test
    # - echo "$SSH_PRIVATE_KEY" > ~/test/gitlab.key
    # - ssh -i gitlab.key andrew@menkent.dev "cd ~/projects && touch testfile && exit"
    # - touch ~/test/testfff
    # - rsync -avz -e "ssh -i ~/test/gitlab.key" ~/test/ andrew@menkent.dev:/home/andrew/projects/
    # - cd ~/projects
    # - touch testfile
    # - ssh andrew@menkent.dev "cd ~/projects && touch testfile && exit"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 755 ~/.ssh
    - mkdir -p ~/test
    - echo "$SSH_PRIVATE_KEY" > ~/test/gitlab.key
    - chmod 600 ~/test/gitlab.key
    - ssh-keyscan menkent.dev >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh -i ~/test/gitlab.key andrew@menkent.dev "cd ~/projects && touch testfile && exit"
  # artifacts:
  #   expire_in: 1 day
  #   paths:
  #     - gitlab.key
