image: trion/ng-cli

stages:
  - build
  - upload

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build_stage:
  stage: build
  environment: Stage
  only:
    - master
  script:
    - rm ./package-lock.json
    - npm install
    - npm run toprod
  artifacts:
    paths:
      - dist/SportPuzzle/
