image: trion/ng-cli

stages:
  - node_modules
  - build
  - upload

cache:
  paths:
    - node_modules/

node_modules:
  stage: node_modules
  environment: Stage
  script:
    # - apt-get update -qq && apt-get install -y -qq sshpass
    # - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    # - echo -e "menkent.dev *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rm ./package-lock.json
    - npm i
  only:
    - master

build_stage:
  stage: build
  environment: Stage
  only:
    - master
  script:
    - npm run toprod
  artifacts:
    expire_in: 1 day
    paths:
      - dist/SportPuzzle/

deploy:
  stage: upload
  environment: Stage
  only:
    - master
  script:
    - echo "$SSH_PRIVATE_KEY" > gitlab.key
    - ssh -i gitlab.key menkent.dev
    - cd ~/projects
    - touch testfile
  # artifacts:
  #   expire_in: 1 day
  #   paths:
  #     - gitlab.key
