image: node:10.15.3

stages:
  - build
  - upload

before_script:
  - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y install tzdata
  - ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
  - apt-get install -y tzdata
  - dpkg-reconfigure --frontend noninteractive tzdata
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - chmod 755 ~/.ssh
  - mkdir -p ~/test
  - echo "${SSH_PRIVATE_KEY}" > ~/test/gitlab.key
  - chmod 600 ~/test/gitlab.key
  - ssh-keyscan menkent.dev >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

build_stage:
  stage: build
  environment: Stage
  only:
    - master
  script:
    - DEBIAN_FRONTEND=noninteractive apt install -y nodejs npm
    - apt install npm -y -qq
    - npm install -g @angular/cli -y -qq
  # - rm ./package-lock.json
    - npm i
    - npm run toprod
  artifacts:
    expire_in: 1 day
    paths:
      - dist/SportPuzzle/

deploy:
  stage: upload
  environment: Stage
  only:
    - master
  script:
    - DEBIAN_FRONTEND=noninteractive apt install -y nodejs npm
    # Пример команды через ssh
    # - ssh -i ~/test/gitlab.key andrew@menkent.dev "cd ~/site-dockers/projects && touch testfile && exit"
    # нужно удалить папку, прежде чем копировать новую туда
    - ssh -i ~/test/gitlab.key andrew@menkent.dev "cd ~/site-dockers/projects/nginx/src && rm -rf dist/SportPuzzle && exit"
    # копирование файлов
    - scp -i ~/test/gitlab.key -r dist/SportPuzzle andrew@menkent.dev:/home/andrew/site-dockers/projects/nginx/src/dist/SportPuzzle
    # нужно сделать настройки для сабдомена nginx, затем так же копировать их в нужную папку
    - scp -i ~/test/gitlab.key deploy-info/nginx-sportpuzzle.conf andrew@menkent.dev:/home/andrew/site-dockers/projects/nginx/config/subdomains/
    # нужно вызвать какой-то restart.nginx.sh для добавления и обновления сабдоменов
    - ssh -i ~/test/gitlab.key andrew@menkent.dev "cd ~/site-dockers/projects/nginx && bash restart.sh && exit"
    # Удачное завершение deploy
    - echo 'Build copied to server'
