image: trion/ng-cli

stages:
  - node_modules
  - build
  - upload

cache:
  paths:
    - node_modules/

node_modules:
  stage: node_modules
  environment: Stage
  only:
    - master
  script:
    - rm ./package-lock.json
    - npm install

build_stage:
  stage: build
  environment: Stage
  only:
    - master
  script:
    - npm run toprod
  artifacts:
    expire_in: 1 day
    paths:
      - dist/SportPuzzle/
